cursos = []

def agregar_profesor(curso, prof):
    globals()["prof" + curso].append(prof)
    return globals()["prof" + curso]

def agregar_curso(curso):
    cursos.append(curso)
    globals()[curso] = []
    globals()["prof" + curso] = []
    globals()["pres" + curso] = []
    return cursos

def agregar_alumno(curso, alumno):
    globals()[curso].append (alumno)
    return globals()[curso]

def lista_alumnos(curso):
    return globals()[curso]


agregar_curso("1°1")
agregar_curso("1°2")
agregar_curso("1°3")
agregar_curso("1°4")
agregar_curso("1°5")
agregar_curso("2°1")
agregar_curso("2°2")
agregar_curso("2°3")
agregar_curso("2°4")
agregar_curso("2°5")
agregar_curso("3°1")
agregar_curso("3°2")
agregar_curso("3°3")
agregar_curso("3°4")
agregar_curso("3°5")
agregar_curso("4°1")
agregar_curso("4°2")
agregar_curso("4°3")
agregar_curso("4°4")
agregar_curso("4°5")
agregar_curso("5°1")
agregar_curso("5°2")
agregar_curso("5°3")
agregar_curso("5°4")
agregar_curso("5°5")
agregar_curso("6°1")
agregar_curso("6°2")
agregar_curso("6°3")
agregar_curso("6°4")
agregar_curso("6°5")
agregar_curso("7°1")
agregar_curso("7°2")
agregar_curso("7°3")
agregar_curso("7°4")
agregar_curso("7°5")


agregar_alumno("1°1", "Alvarez ")
agregar_alumno("1°1", "Echeveria ")
agregar_alumno("1°1", "Silva  ")
agregar_alumno("1°1", "Gonzales ")
agregar_alumno("1°1", "Nuñez ")
agregar_alumno("1°2", "Guarnizo ")
agregar_alumno("1°2", "Troche ")
agregar_alumno("1°2", "Banco ")
agregar_alumno("1°2", "Biri ")
agregar_alumno("1°2", "Dramajo ")
agregar_alumno("1°3", "Wilt ")
agregar_alumno("1°3", "Rojas ")
agregar_alumno("1°3", "Martinez ")
agregar_alumno("1°3", "Piñero ")
agregar_alumno("1°3", "Andrade ")
agregar_alumno("1°4", "Cruz ")
agregar_alumno("1°4", "Espluga ")
agregar_alumno("1°4", "Urreiztieta ")
agregar_alumno("1°4", "Lisboa ")
agregar_alumno("1°4", "Vargas ")
agregar_alumno("1°5", "Govea ")
agregar_alumno("1°5", "Landino ")
agregar_alumno("1°5", "Bravo ")
agregar_alumno("1°5", "Peña ")
agregar_alumno("1°5", "Barroso ")

agregar_alumno("2°1", "Morales ")
agregar_alumno("2°1", "Lopez ")
agregar_alumno("2°1", "Acosta ")
agregar_alumno("2°1", "Hernandez ")
agregar_alumno("2°1", "Alonso ")
agregar_alumno("2°2", "Torres ")
agregar_alumno("2°2", "Sanchez ")
agregar_alumno("2°2", "Guitierrez ")
agregar_alumno("2°2", "Suares ")
agregar_alumno("2°2", "Rodriguez ")
agregar_alumno("2°3", "Rojas ")
agregar_alumno("2°3", "Reyes ")
agregar_alumno("2°3", "Mendez ")
agregar_alumno("2°3", "Castillo ")
agregar_alumno("2°3", "Morillo ")
agregar_alumno("2°4", "Socorro ")
agregar_alumno("2°4", "Corona ")
agregar_alumno("2°4", "Morillo ")
agregar_alumno("2°4", "Atencion ")
agregar_alumno("2°4", "Marquez ")
agregar_alumno("2°5", "Govea ")
agregar_alumno("2°5", "Romero ")
agregar_alumno("2°5", "Piñero ")
agregar_alumno("2°5", "Landino ")
agregar_alumno("2°5", "Garcia ")

agregar_alumno("3°1", "Lubo ")
agregar_alumno("3°1", "Montero ")
agregar_alumno("3°1", "Velarde ")
agregar_alumno("3°1", "Añez ")
agregar_alumno("3°1", "Muñoz ")
agregar_alumno("3°2", "Arroyo ")
agregar_alumno("3°2", "Soria ")
agregar_alumno("3°2", "Ortiz ")
agregar_alumno("3°2", "Palma ")
agregar_alumno("3°2", "Quispe ")
agregar_alumno("3°3", "Flores ")
agregar_alumno("3°3", "Ruis ")
agregar_alumno("3°3", "Gomez ")
agregar_alumno("3°3", "Cruzado ")
agregar_alumno("3°3", "Huaman ")
agregar_alumno("3°4", "Rivera")
agregar_alumno("3°4", "Jimenez ")
agregar_alumno("3°4", "Torres ")
agregar_alumno("3°4", "Iglesias ")
agregar_alumno("3°4", "Vera ")
agregar_alumno("3°5", "Heras ")
agregar_alumno("3°5", "Gallego ")
agregar_alumno("3°5", "Moreno")
agregar_alumno("3°5", "Cortes ")
agregar_alumno("3°5", "Dominguez")

agregar_alumno("4°1", "Vazquez ")
agregar_alumno("4°1", "Ayala ")
agregar_alumno("4°1", "Diez ")
agregar_alumno("4°1", "Mora ")
agregar_alumno("4°1", "Cabral ")
agregar_alumno("4°2", "Jacobo ")
agregar_alumno("4°2", "Henriquez ")
agregar_alumno("4°2", "Galeano ")
agregar_alumno("4°2", "Taco ")
agregar_alumno("4°2", "Ulate ")
agregar_alumno("4°3", "Quinter")
agregar_alumno("4°3", "Zacasa ")
agregar_alumno("4°3", "Quezada ")
agregar_alumno("4°3", "Elmaleh ")
agregar_alumno("4°3", "Vadivia ")
agregar_alumno("4°4", "Yurica ")
agregar_alumno("4°4", "Lagos ")
agregar_alumno("4°4", "Quijada ")
agregar_alumno("4°4", "Abella ")
agregar_alumno("4°4", "Madrano ")
agregar_alumno("4°5", "Saboyal ")
agregar_alumno("4°5", "Kuadra ")
agregar_alumno("4°5", "Urbano ")
agregar_alumno("4°5", "Damito ")
agregar_alumno("4°5", "Faeth ")

agregar_alumno("5°1", "")
agregar_alumno("5°1", "")
agregar_alumno("5°1", "")
agregar_alumno("5°1", "")
agregar_alumno("5°1", "")
agregar_alumno("5°2", "Blanco Martin")
agregar_alumno("5°2", "Bustamante Mia")
agregar_alumno("5°2", "Casanovas Roberto")
agregar_alumno("5°2", "Bordon Luciano")
agregar_alumno("5°2", "Santacruz Mauricio")
agregar_alumno("5°3", "Ianuzzi Thiago")
agregar_alumno("5°3", "Fernandez Luna")
agregar_alumno("5°3", "Paredes Adrian")
agregar_alumno("5°3", "Villanueva karina")
agregar_alumno("5°3", "Alvarez Carlos")
agregar_alumno("5°4", "Gonzalez Juan")
agregar_alumno("5°4", "Schneider Ian")
agregar_alumno("5°4", "Calo Rodrigo")
agregar_alumno("5°4", "Paredes Melody")
agregar_alumno("5°4", "Gonzales Melanie")
agregar_alumno("5°5", "Irastorza ")
agregar_alumno("5°5", "Laine ")
agregar_alumno("5°5", "Balday ")
agregar_alumno("5°5", "Raigosa ")
agregar_alumno("5°5", "Paises ")

agregar_alumno("6°1", "Taracena ")
agregar_alumno("6°1", "Dasadre ")
agregar_alumno("6°1", "Juncos ")
agregar_alumno("6°1", "Bermudez ")
agregar_alumno("6°1", "Lubo ")
agregar_alumno("6°2", "Morillo ")
agregar_alumno("6°2", "Duarte ")
agregar_alumno("6°2", "Finol ")
agregar_alumno("6°2", "Andrade ")
agregar_alumno("6°2", "Quispe ")
agregar_alumno("6°3", "Zambrano ")
agregar_alumno("6°3", "Baca")
agregar_alumno("6°3", "Barva ")
agregar_alumno("6°3", "Grimaldi ")
agregar_alumno("6°3", "Romano ")
agregar_alumno("6°4", "Moretti ")
agregar_alumno("6°4", "D´agosito")
agregar_alumno("6°4", "Marchetti")
agregar_alumno("6°4", "Giordano ")
agregar_alumno("6°4", "Palmieri ")
agregar_alumno("6°5", "Salerno ")
agregar_alumno("6°5", "Diaz ")
agregar_alumno("6°5", "Perez ")
agregar_alumno("6°5", "Sosa ")
agregar_alumno("6°5", "Benitez ")

agregar_alumno("7°1", "Salazar ")
agregar_alumno("7°1", "Ramirez ")
agregar_alumno("7°1", "Muñoz ")
agregar_alumno("7°1", "Gutierrez ")
agregar_alumno("7°1", "Mamani ")
agregar_alumno("7°2", "Liquin ")
agregar_alumno("7°2", "Vilte ")
agregar_alumno("7°2", "Lacsi ")
agregar_alumno("7°2", "Lamas ")
agregar_alumno("7°2", "Chocobar ")
agregar_alumno("7°3", "Chiri ")
agregar_alumno("7°3", "Alancay ")
agregar_alumno("7°3", "Caiconde ")
agregar_alumno("7°3", "Socomba ")
agregar_alumno("7°3", "Puca ")
agregar_alumno("7°4", "Peloc ")
agregar_alumno("7°4", "Mecabell ")
agregar_alumno("7°4", "Aranda ")
agregar_alumno("7°4", "Zapata ")
agregar_alumno("7°4", "Rabinad ")
agregar_alumno("7°5", "Pastor ")
agregar_alumno("7°5", "Capella ")
agregar_alumno("7°5", "Maggi ")
agregar_alumno("7°5", "Racca ")
agregar_alumno("7°5", "Fiuorani ")


